exports.ACCOUNT_IS_ALREADY_EXIST = 1;
exports.ADD_ACCOUNT_SUCCESS = 2;
exports.EDIT_CUSTOMERINFO_SUCCESS = 3;
exports.EDIT_CUSTOMERINFO_FAILED = 4;

exports.PAYMENTMETHOD_UNPAID = 0;
exports.PAYMENTMETHOD_PAID = 1;
exports.ORDER_REQUESTING = 1;
exports.ORDER_PENDING = 2;
exports.ORDER_SUCCESS = 3;
exports.SHIPPING_PENDING = 1;